# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - git clone --branch gh-pages https://github.com/marmita-de-redon/website.git
    - mkdir -p $READTHEDOCS_OUTPUT/html
    # - pip install mkdocs
    - pwd
    - ls -al
    - cp -r website/* $READTHEDOCS_OUTPUT/html/
    # - mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
    - pwd
    - ls -al
    - echo $READTHEDOCS_OUTPUT/html
    - ls -al $READTHEDOCS_OUTPUT/html

  # jobs:
  #   post_build:
  #     - pwd
  #     - ls -al
  #     - ls -al _readthedocs/html

# mkdocs:
#   configuration: mkdocs.yml

# # Optionally declare the Python requirements required to build your docs
# python:
#   install:
#     - requirements: docs/requirements.txt
